<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOH7TQEa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOH7TQEa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOH7TQEa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOH7TQEa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOH7TQEa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OH7TQEa',
    'container.build_id' => 'd1591e05',
    'container.build_time' => 1562057679,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOH7TQEa');
