<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPNuYypy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPNuYypy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPNuYypy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPNuYypy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPNuYypy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PNuYypy',
    'container.build_id' => 'f08162ce',
    'container.build_time' => 1562075770,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPNuYypy');
